x-lawn:
  compatibility:
    minLawnVersion: 0.2.0

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.3.0
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      xpack.security.transport.ssl.enabled: "false"
      xpack.security.http.ssl.enabled: "false"
      cluster.name: lawn-elasticsearch
      http.host: "0.0.0.0"
      cluster.routing.allocation.disk.threshold_enabled: "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - "./data:/usr/share/elasticsearch/data"
    ports:
      - "9200:9200"
    deploy:
      resources:
        limits:
          memory: 2048M
    x-lawn:
      healthChecks:
        - id: elasticsearch-api
          type: http
          path: /
          expectedStatus: 200
          startPeriodSeconds: 100
          intervalSeconds: 5
          timeoutSeconds: 5
          retries: 30
      environment:
        discovery.type:
        xpack.security.enabled:
        xpack.security.transport.ssl.enabled:
        xpack.security.http.ssl.enabled:
        cluster.name:
        http.host:
        cluster.routing.allocation.disk.threshold_enabled:
        ES_JAVA_OPTS:
