x-lawn:
  compatibility:
    minLawnVersion: 0.2.0

services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.10.2
    environment:
      PUID: "${UID:-1000}"
      PGID: "${GID:-1000}"
      TZ: "${TIMEZONE:-UTC}"
      ALLOW_SIGNUP: "false"
      BASE_URL: "${LAWN_URL:-}"
    volumes:
      - "./data:/app/data"
    ports:
      - "9925:9000"
    deploy:
      resources:
        limits:
          memory: 1024M
    x-lawn:
      healthChecks:
        - id: web-ui
          type: http
          path: /api/app/about
          expectedStatus: 200
          startPeriodSeconds: 90
      environment:
        PUID:
        PGID:
        TZ:
        ALLOW_SIGNUP:
        BASE_URL:
